require 'active_record'
require 'yaml'
require 'logger'

# command to move to a specific version, say 003:
# => rake migrate VERSION=003

task :default => :migrate

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil )
end

task :environment do
  ActiveRecord::Base.establish_connection(YAML::load(File.open('db/config/database.yml')))
  ActiveRecord::Base.logger = Logger.new(File.open('db/log/database.log', 'a'))
end